---
# source
#https://knowledgegainedandshared.com/2021/03/08/how-to-run-windows-updates-with-ansible/
#
- name: update hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Search and download Windows updates without installing
      win_updates:
        state: downloaded
    - name: Install all updates without a schedule tasks
      win_updates:
        server_selection: windows_update
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - DefinitionUpdates
        reboot: yes
        log_path: C:\beheer\Win_Template_Patch.log