- name: Set timezone
  win_timezone:
    timezone: "{{ timezone }}"

- name: Set language
  win_region:
    unicode_language: "{{ unicode_language }}"
  register: result

- name: Reboot if required
  win_reboot:
  when: result.restart_required
